---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    name: nexus-pv
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
  storageClassName: nexus-local
  accessModes:
    - ReadWriteOnce
  capacity:
     storage: 20Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/nexus-data-0"