---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  labels:
    name: nexus-pvc 
spec:
  storageClassName: nexus-local
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  selector:
    matchLabels:
      name: nexus-pv
    # matchExpressions:
    #   - key: kubernetes.io/hostname
    #     operator: In
    #     values:
    #       - worker-docker-2